/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { FanToken } from "./FanToken";
export type { NFT } from "./NFT";
export type { Universe } from "./Universe";
